a = "My name is Shehryar"
print(a)
print(len(a))
print(a.upper())
print(a.lower())
print(a.replace("Shehryar", "Harry"))
print(a.split(" "))
print(a.rstrip("r"))
b = "my name is Shehryar"
print(b)
print(b.capitalize())
print(b.title())
print(b.startswith("my"))
print(b.endswith("Shehryar"))
print(b.find("is"))
print(b.index("is"))
print(b.isalnum())
print(b.isalpha())
print(b.isdigit())
print(b.islower())
print(b.isupper())
print(b.count("a"))
print(b.center(50, "*"))
print(b.istitle())