UserInput = str(input("Enter A String:"))
print("Occurances of 'a' in the String :", UserInput.count('a'))
print("Does the String end with 'a'?", UserInput.endswith('a'))
print("Capitalized String:", UserInput.capitalize())
print("Replacing 'b' with 'c':", UserInput.replace('b', 'c'))
print("Finding 'a' in the String:", UserInput.find('a'))
print("Does the String start with 'a'?", UserInput.startswith('a'))
print("String Slicing (0:5):", UserInput[0:5])
print("String Slicing (-4:-1):", UserInput[-4:-1])